name: "Release-Windows"
on:
  release:
    types: ["published"]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: "master"

    - name: Wait for package update
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'Update-Package'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v3

    - name: Restore dependencies
      run: yarn install

    - name: Build Typescript
      run: yarn build-tsc

    - name: Build for Windows
      run: yarn build-win
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./dist/*.exe

    - name: "Upload Artifacts to Release"
      uses: "ncipollo/release-action@v1"
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: "dist/*.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true