name: "Update-Package"
on:
  release:
    types: ["published"]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: "master"
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Make Release Changes
      uses: jaywcjlove/github-action-package@main
      with:
        version: ${{ github.event.release.tag_name }}

    - name: Commit Release Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: "master"
        commit_message: "Version ${{ env.version }} [deploy-skip]"
        commit_user_name: "CPA-Client"

    

    